### ISSUE TITLE
it doesn't run on win

### ISSUE THREAD

**Issue by djaonourside** [jeremyfa/haxe-xmlgrammar#1]
Win 8, haxe 4 preview 4. 
After command `haxelib run xmlgrammar --yaml` I got the error:
 Called from sys/ssl/Socket.hx line 68
 Uncaught exception - load.c(237) : Failed to load library : hxssl.ndll

**Comment by jeremyfa** [comment]
Apparently hxssl is already built-in since haxe 3.3+ so is probably unnecessary. Will remove it, check that it sill works and publish the lib again.

Thanks for reporting!

**Comment by jeremyfa** [comment]
Done, you can try v0.1.2, it should fix this issue

**Comment by djaonourside** [comment]
Thank you very much. Now it works.
